name: phd
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - kedro==0.18.14
  - pandas
  - matplotlib
  - scipy
  - statsmodels
  - sympy
  - scikit-learn
  - dill
  - plotly_express
  - jupyterlab
  - geopandas
  - arviz
  - seaborn
  - pip:
    - vessel-manoeuvring-models==0.0.18
    - pyfiglet
    - pysindy==1.7.5cs
    - ipynbname